openapi: 3.0.1
info:
  title: RE-Miner HUB
  description: RE-Miner HUB is a component that integrates multiple NLP models for both feature extraction and emotion classification tasks
  version: 1.0.0
servers:
- url: http://localhost:3002/
- url: http://gessi-sw.essi.upc.edu:3002/
paths:
  /analyze:
    post:
      summary: Analyze reviews
      description: Analyzes reviews for sentiment and feature extraction
      operationId: analyze
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sentiment_model:
                  type: string
                  description: The sentiment analysis model to use (optional)
                  enum: ["BERT", "BETO", "GPT-3.5"]
                feature_model:
                  type: string
                  description: The feature extraction model to use (optional)
                  enum: ["transfeatex", "t-frex-bert-base-uncased", "t-frex-bert-large-uncased", "t-frex-roberta-base", "t-frex-roberta-large", "t-frex-xlnet-base-cased", "t-frex-xlnet-large-cased"]
                text:
                  type: string
                  description: The text to analyze
              required:
                - text
      responses:
        '200':
          description: An array of analyzed reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AnalyzedReview'
        '400':
          description: Bad request format
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string